blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView', 
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

noticias/urls.py
from django.urls import path
from .views import *

app_name = 'noticias'

urlpatterns =   [
    path('', HomePageView, name = "home"),
    # path('portafolio/servicios/', ListServiceView.as_view(), name = "servicios"),
    # path('portafolio/sistemas/', ListPortfolioView.as_view(), name = "portafolio1"),
    path('historia-simas/', HistoriaPageView.as_view(), name = "historia"),
    # path('quienes-somos/', QuienesPageView.as_view(), name = "somos"),
    path('noticias/', ListNewsView.as_view(), name = "noticias"),
   	path('noticias/<int:id>/<str:uri>/', DetailNewsView, name = "detalle-noticia"),
    path('contactenos/', ContactenosPageView.as_view(), name = "contactenos"),
    path('noticias/categoria/<str:slug>', notas_categoria, name = "list-noticia-cat")
]


websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),    
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

blogs/models.py
from django.db import models
from otras.models import Autor
from publicaciones.models import Tematica
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.template.defaultfilters import slugify
from sorl.thumbnail import ImageField
from websimas.utils import get_file_path

# Create your models here.

class Catblog(models.Model):
    catblog = models.CharField('Categoria del blog', max_length=350, blank=True, null=True)

    def __str__(self):
        return self.catblog

class Blog(models.Model):
    blog = models.CharField(max_length=500, blank=True, null=True)
    idautor = models.ForeignKey(Autor, verbose_name="Autor", blank=True, null=True, on_delete = models.CASCADE)
    fecha = models.DateField(blank=True, null=True)
    #descripcion = models.TextField(blank=True, null=True)
    foto = ImageField( upload_to=get_file_path, blank=True, null=True)
    credito = models.CharField(max_length=200, blank=True, null=True) 
    uri = models.CharField(max_length=500, blank=True, null=True, editable=False)
    idcatblog = models.ForeignKey('Catblog', verbose_name='Categoria del blog',blank=True, null=True, on_delete = models.CASCADE)   
    resumen = RichTextUploadingField(blank=True, null=True)
    tags = models.CharField(max_length=300, blank=True, null=True)
    tematica = models.ManyToManyField(Tematica, verbose_name='Tematica del blog', blank=True)

    fileDir = 'fotoBlogs/'

    def save(self, *args, **kwargs):  
        add = not self.pk
        super(Blog, self).save(*args, **kwargs)
        if add:
            self.uri = (slugify(self.blog)) + '-' + str(self.id)
            kwargs['force_insert'] = False # create() uses this, which causes error.
            super(Blog, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog_detalle', kwargs={'slug': self.uri})

    def __str__(self):
        return self.blog

blogs/forms.py
from django import forms
from .models import Catblog

class TagForm(forms.Form):
	tag = forms.ModelChoiceField(queryset=Catblog.objects.all(),
		widget=forms.Select(attrs={'class':'dropdownblog'}))

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from blogs.models import *
from blogs.forms import TagForm
from otras.models import MenuFoto

# Create your views here.
class ListBlogsView(ListView):
    model = Blog
    queryset = Blog.objects.order_by('-fecha')
    # paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(ListBlogsView, self).get_context_data(**kwargs)
        context['form_tag'] = TagForm()
        context['tags'] = Catblog.objects.all()
        # context['foto_blog'] = MenuFoto.objects.get(menu=5)

        return context


def DetailBlogsView(request, template='blogs/detalle_blog.html', id=None, uri=None):
    nota = get_object_or_404(Blog, id=id)

    lista_tematicas = nota.idcatblog

    try:
        noticias_relacionadas = Blog.objects.filter(idcatblog=lista_tematicas).exclude(id=nota.id).order_by('-id')[:3]
    except:
        pass

    # foto_blog = MenuFoto.objects.get(menu=5)

    return render(request, template, locals())


def blogs_filtrados(request, template="blogs/blog_list.html"):
    object_list = Blog.objects.filter(idcatblog=request.POST["tag"])
    tags = Catblog.objects.all()
    foto_blog = MenuFoto.objects.get(menu=5)
    return render(request, template, locals())

templates/sitio_v2/blogs/blog_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% load embed_video_tags %}
{% load el_pagination_tags %}
{% block extra_css %}
<style>
.pagination>.active{
	background: #089c7b;
    color: #fff;
    border-color: #089c7b;
}
.page-link {
    color: #888;
    border: 2px solid rgba(74,156,124,0.38);
    -webkit-transition: all 0.4s ease;
    -moz-transition: all 0.4s ease;
    -o-transition: all 0.4s ease;
    transition: all 0.4s ease;
}

.page-link:hover {
    background: #089c7b;
    color: #fff;
    border-color: #089c7b;
    -moz-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    -webkit-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}
</style>
{% endblock extra_css %}
{% block content %}
<div class="breadcrumb-area shadow dark bg-fixed text-center color-white" >
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 text-left">
                <h2 >Cambiando Vidas</h2>
            </div>
            <div class="col-md-6 col-sm-6 text-right">
                <ul class="breadcrumb">
                    <li><a href="/">Inicio</a></li>
                    <li class="active">Cambiando Vidas</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="area-noticia padding-page bg-gris ">
    <div class="container">
        <div class="row">
          {% paginate 9 object_list %}
		  {% for obj in object_list %}
		  <div class="col-md-4 mrb-20">
				<div class="card box-shadow">
					<div class="entry-thumbnail">
						<a href="{% url 'blogs:detalle-blog' obj.id obj.uri %}">
							{% thumbnail obj.foto "800x480" crop="center" as im %}
								<img src="{{ im.url }}" class="card-img-top">
							{% empty %}
								<img src="https://place-hold.it/800x480" class="card-img-top" alt="...">
							{% endthumbnail %}
						</a>
						<div class="card-author">
							{% comment %} <span class="xs-round-avatar">
								{% thumbnail obj.idautor.imagen "42x42" crop="center" as im %}
                                <img src="{{ im.url }}" class="img-responsive" alt="{{obj.idautor}}">
                                {% empty %}
                                <img src="https://place-hold.it/42x42" class="img-responsive" alt="{{obj.idautor}}">
                                {% endthumbnail %}
							</span> {% endcomment %}
							<span class="author-name">
								<a href="#">por {{obj.idautor}}</a>
							</span>
						</div>
						<span class="badge badge-main" style="background-color:#3DB4D9;">{{obj.idcatobj}}</span>
					</div>
					<div class="card-body">
						<div class="card-tags">
							
							<span class="date">{{obj.fecha|date:"d F, Y"}}</span>
						</div>
						<h5 class="card-title text-limit line-2">
						<a href="{% url 'blogs:detalle-blog' obj.id obj.uri %}">{{obj.blog}}</a>
						</h5>
					</div>
					<div class="separador"></div>
					<div class="card-meta">
						<span class="comments-link">
							<i class="fa fa-comments"></i>
							<a href="">300 Comentarios</a>
						</span><!-- .comments-link -->
						<!--<span class="view-link">
							<i class="fa fa-eye"></i>
							<a href="">1000 Vistas</a>
						</span>-->
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		<nav class="paginador mrt-30">
			<ul class="pagination justify-content-center">
			  <!--<li class="page-item">
				<a class="page-link" href="#"><i class="fa fa-angle-left"></i></a>
			  </li>
			  <li class="page-item active"><a class="page-link" href="#">1</a></li>
			  <li class="page-item"><a class="page-link" href="#">2</a></li>
			  <li class="page-item disabled"><a class="page-link">...</a></li>
			  <li class="page-item"><a class="page-link" href="#">80</a></li>
			  <li class="page-item"><a class="page-link" href="#">81</a></li>
			  <li class="page-item">
				<a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
			  </li>-->
			  {% show_pages %}
			</ul>
		</nav>
	</div>
</div>

{% endblock content %}

{% block extra_js %}
<script>
	$(".menu-4").addClass("active");
    $(".endless_page_link").addClass("page-link page-item");
    $(".endless_page_current").addClass("page-link active page-item");
</script>
{% endblock extra_js %}

templates/sitio_v2/blogs/detalle_blog.html
{% extends "base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% block content %}

<div class="breadcrumb-area shadow dark bg-fixed text-center color-white" >
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 text-left">
                <h2 >Cambiando Vidas</h2>
            </div>
            <div class="col-md-6 col-sm-6 text-right">
                <ul class="breadcrumb">
                    <li><a href="/">Inicio</a></li>
                    <li><a href="/noticias/">Cambiando Vidas</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<Article class="area-noticia padding-page bg-gris ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="noticia">
                    {% if nota.url %}
                    <div class="video-noticia">
                        <iframe width="100%" height="315" src="https://www.youtube.com/embed/sz13mYFugIM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                    {% else %}
                    <div class="img-noticia">
                        <figure class="figure">
                            {% thumbnail nota.foto "800x480" crop="center" as img %}
                                <img class="img-responsive figure-img" src="/media/{{img}}" alt="" >
                            {% endthumbnail %} 
                            <figcaption class="figure-caption">
                                <span class='fa fa-image'></span> {{nota.credito}}
                            </figcaption>
                        </figure>
                        
                    </div>
                    {% endif %}
                
                    <div class="info-noticia box-shadow">
                        <div class="info-title">
                            <div class="date">
                                <span>{{nota.fecha|date:"d"}}</span> 
                                <span>{{nota.fecha|date:"M"}}</span>
                                <span>{{nota.fecha|date:"y"}}</span>
                            </div>
                            <div class="title">
                                <h3>{{nota.blog}}</h3>
                                <div class="meta">
                                    <div class="position-relative">
                                        {% comment %} <span class="round-avatar">
                                            {% thumbnail nota.idautor.imagen "42x42" crop="center" as im %}
                                            <img src="{{ im.url }}" class="img-responsive" alt="{{nota.idautor}}">
                                            {% empty %}
                                            <img src="https://place-hold.it/42x42" class="img-responsive" alt="{{nota.idautor}}">
                                            {% endthumbnail %}
                                        </span> {% endcomment %}
                                        <p class>
                                        {{nota.idautor}}
                                        </p>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="info-texto">
                            {{nota.resumen|safe }}
                        </div>
                    </div>
                </div>
                <div class="noticia-tags">
                    <span>Temáticas: </span>
                    {%for tema in nota.tematica.all%}
                    <a href="#">{{tema}}</a>
                    {%endfor%}
                </div>
            </div>
        </div>
    </div>
</Article>



<div class="si-sticky" style="margin-top: -210px;">
    <a href="#" class="social-icon si-facebook brand bounceInLeft animated" data-animate="bounceInLeft">
        <i class="fa fa-facebook-f"></i>
    </a>
    <a href="#" class="social-icon si-twitter brand bounceInLeft animated" data-animate="bounceInLeft" data-delay="100">
        <i class="fa fa-twitter"></i>
    </a>
    <a href="#" class="social-icon si-whatsapp brand bounceInLeft animated" data-animate="bounceInLeft" data-delay="200">
        <i class="fa fa-whatsapp"></i>
    </a>
    <a href="#" class="social-icon si-envelope bounceInLeft animated" data-animate="bounceInLeft" data-delay="300">
        <i class="fa fa-envelope"></i>
    </a>
    
</div>

<div class="socialshare-xs">
    <ul>
        <li class="label-social">
           <a class="">Compartir:</a>
        </li>
        <li>
            <a href="#" class="social-icon si-facebook brand bounceInLeft animated" data-animate="bounceInLeft">
                <i class="fa fa-facebook-f"></i>
            </a>
        </li>
        <li>
            <a href="#" class="social-icon si-twitter brand bounceInLeft animated" data-animate="bounceInLeft" data-delay="100">
                <i class="fa fa-twitter"></i>
            </a>
        </li>
        <li>
            <a href="#" class="social-icon si-whatsapp brand bounceInLeft animated" data-animate="bounceInLeft" data-delay="200">
                <i class="fa fa-whatsapp"></i>
            </a>
        </li>
        <li>
            <a href="#" class="social-icon si-envelope bounceInLeft animated" data-animate="bounceInLeft" data-delay="300">
                <i class="fa fa-envelope"></i>
            </a>
        </li>
    </ul>
</div>


<!--<section class="list-blog bg-gris pdb-100">

    <div class="container">
		<div class="row">
			<div class="col">
				<div class="seccion-heading-style-two mrb-30">
					<h2 class="text-color-base">Noticias Relacionadas</h2>
				</div>
			</div>
		</div>
        <div class="row">
            {% if nota.tipo != 2 %}
            {% for relacion in noticias_relacionadas %}
            <div class="col-md-4">
                <div class="card box-shadow">
                
                    <div class="entry-thumbnail">
                    {% if relacion.foto %}
                        {% thumbnail relacion.foto "348x209" crop="10%" as img %}  
                        <a href="{% url 'noticias:detalle-noticia' relacion.id relacion.uri %}">
                            <img class="img-responsive figure-img" src="/media/{{img}}" alt="" >
                        </a>
                        {% endthumbnail %}
                    {% else%}
                        <a href="{% url 'noticias:detalle-noticia' relacion.id relacion.uri %}">
                            <img class="img-responsive figure-img" src="https://place-hold.it/348x209" alt="" >
                        </a>
                    {% endif %}
                        <div class="card-author">
                            <span class="xs-round-avatar">
                                <img class="img-responsive" src="https://place-hold.it/42x42" alt="" >
                            </span>
                            <span class="author-name">
                                <a href="#">{{relacion.idautor}}</a>
                            </span>
                        </div>
                        <span class="badge badge-main" style="background-color:#3DB4D9;">Tecnología</span>
                    </div>
                    <div class="card-body mrt-10">
						<div class="card-tags">
							
							<span class="date">{{relacion.fecha|date:"d M Y"}}</span>
						</div>
                      	<h5 class="card-title">
						  <a href="{% url 'noticias:detalle-noticia' relacion.id relacion.uri %}">{{relacion.noticia}}</a>
                        </h5>
                    </div>
                
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>

    </div>
    
</section>-->
{% endblock content %}
{% block extra_js %}
<script>
	$(".menu-4").addClass("active");
</script>
{% endblock extra_js %}