blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView', 
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

publicaciones/urls.py
from django.urls import path, include
from .views import *

app_name = 'publicaciones'

urlpatterns = [
    path('publicaciones/', ListBooksView, name ='publicaciones'),
    path('publicaciones/filtro/<id>', FiltroListBooksView, name ='filtro-publicaciones'),
    path('publicaciones/<int:id>/<str:uri>/', DetailBooksView, name ='detalle-publicacion'),
    # path('publicaciones/simas/', ListBookSimasView.as_view(), name ='publicaciones'),
    # path('publicaciones/cidoc/', ListBookCidocView.as_view(), name ='publicaciones'),
    path('publicaciones/categoria/<str:slug>', publicaciones_categoria, name = "list-publicaciones-cat")
]



""" urlpatterns = patterns(
    'publicaciones.views',
    url(r'^publicaciones/$', ListBooksView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/(?P<id>[0-9]+)/(?P<uri>[-\w]+)/$',
        'DetailBooksView', name='detalle-publicacion'),
    url(r'^publicaciones/simas/$', ListBookSimasView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/cidoc/$', ListBookCidocView.as_view(),
        name='publicaciones'),
)
 """

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),    
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

publicaciones/models.py
# -*- coding: utf-8 -*-
from django.db import models
from ckeditor.fields import RichTextField
from sorl.thumbnail import ImageField, get_thumbnail
from django.template.defaultfilters import slugify
from websimas.utils import get_file_path
from django.urls import reverse
from otras.models import *

# Create your models here.


class Tematica(models.Model):
    tematica = models.CharField(max_length=300, blank=True)
    uri = models.CharField(max_length=150, blank=True)
    foto = models.CharField(max_length=255, blank=True)
    texto = models.TextField(blank=True)
    fecha = models.DateField(blank=True, null=True)
    orden = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = "Tematica"
        verbose_name_plural = "Tematicas"

    def __str__(self):
        return self.tematica


class Tipopublicacion(models.Model):
    tipopublicacion = models.CharField(max_length=300, null=True, blank=True)

    class Meta:
        verbose_name = 'Tipo Publicación'
        verbose_name_plural = 'Tipos de publicaciones'


    def __str__(self):
        return self.tipopublicacion


class Disponibilidad(models.Model):
    disponibilidad = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = 'disponibilidad'
        verbose_name_plural = 'disponibilidades'


    def __str__(self):
        return self.disponibilidad

TIPO_PUB_CHOICES = ((1,'Sistematización'),(2,'Publicación'))

class Publicacion(models.Model):
    # idtematica = models.ManyToManyField(Tematica, verbose_name="Tematicas",blank=True)
    autor = models.CharField(max_length=300, blank=True, null=True)
    edicion = models.CharField(max_length=200, blank=True, null=True)
    fecha = models.DateField(max_length=50, blank=True, null=True)
    lugar = models.CharField(max_length=200, blank=True, null=True)
    editorial = models.CharField(max_length=2000, blank=True, null=True)
    paginas = models.CharField(max_length=50, blank=True, null=True)
    isbn = models.CharField(max_length=50, blank=True, null=True)
    codigo = models.CharField(max_length=50, blank=True, null=True)
    resumen = RichTextField(blank=True, null=True)
    portada = ImageField(upload_to=get_file_path, blank=True, null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    idtipodocumento = models.IntegerField(blank=True, null=True)
    iddisponibilidad = models.ForeignKey(Disponibilidad, verbose_name='Disponibilidad', blank=True, null=True, on_delete = models.CASCADE )
    nombre1 = models.CharField(max_length=250, blank=True, null=True)
    archivo1 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    nombre2 = models.CharField(max_length=250, blank=True, null=True)
    archivo2 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    nombre3 = models.CharField(max_length=250, blank=True, null=True)
    archivo3 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    nombre4 = models.CharField(max_length=250, blank=True, null=True)
    archivo4 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    nombre5 = models.CharField(max_length=250, blank=True, null=True)
    archivo5 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    nombre6 = models.CharField(max_length=250, blank=True, null=True)
    archivo6 = models.FileField(upload_to=get_file_path, blank=True, null=True)
    tematicaanterior = models.CharField(max_length=1500, blank=True, null=True)
    actualizado = models.NullBooleanField()
    notas = models.TextField(blank=True, null=True)
    publicar = models.NullBooleanField()
    idtipopublicacion = models.IntegerField(blank=True, null=True)
    tipo_publicacion = models.ForeignKey(Tipopublicacion, blank=True, null=True, on_delete = models.CASCADE)
    publicacion = models.CharField(max_length=500, blank=True, null=True)
    claves = models.CharField(max_length=1500, blank=True, null=True)
    enlace = models.CharField(max_length=500, blank=True, null=True)
    uri = models.CharField(max_length=500, blank=True, null=True)
    cidoc = models.NullBooleanField()
    archivo = models.CharField(max_length=500, blank=True, null=True)
    titulo1 = models.CharField(max_length=300, blank=True, null=True)
    titulo2 = models.CharField(max_length=300, blank=True, null=True)
    titulo3 = models.CharField(max_length=300, blank=True, null=True)
    titulo4 = models.CharField(max_length=300, blank=True, null=True)
    titulo5 = models.CharField(max_length=300, blank=True, null=True)
    idtematica2 = models.IntegerField(blank=True, null=True)
    archivo7 = models.CharField(max_length=255, blank=True, null=True)
    nombre7 = models.CharField(max_length=255, blank=True, null=True)
    estado = models.CharField(max_length=1, blank=True)
    idpublicacion2 = models.IntegerField(blank=True, null=True)
    sinfecha = models.NullBooleanField()
    enportada = models.NullBooleanField()
    idcategoria = models.ManyToManyField(Categoria,blank=True,verbose_name='Categoria')
    tipo = models.IntegerField(choices=TIPO_PUB_CHOICES,blank=True, null=True)

    fileDir = 'publicaciones/'

    def save(self, *args, **kwargs):
        self.uri = (slugify(self.publicacion))
        super(Publicacion, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detalle_publicacion', kwargs={'uri': self.uri})

    class Meta:
        verbose_name = 'Publicación'
        verbose_name_plural = 'Publicaciones'

        ordering = ('-id',)

    def __str__(self):
        return self.publicacion

    def get_thumb(self):
      im = get_thumbnail(self.portada, '350x453', crop='center', quality=99)
      return im.url

    def categorias(self):
        return ", ".join([str(p) for p in self.idcategoria.all()])

publicaciones/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Publicacion
from otras.models import MenuFoto

# Create your views here.


def ListBooksView(request, template='publicaciones/publicacion_list.html'):
    object_list = Publicacion.objects.filter(iddisponibilidad=4).order_by('-fecha')
    # context['foto_publi'] = MenuFoto.objects.get(menu=2)
    tematicas = Publicacion.objects.values_list('idcategoria__id','idcategoria__nombre').order_by('idcategoria__id').distinct('idcategoria__id').exclude(idcategoria__nombre = None)

    return render(request, template, locals())

def FiltroListBooksView(request,id,template='publicaciones/publicacion_list.html'):
    object_list = Publicacion.objects.filter(iddisponibilidad=4,idcategoria__id=id).order_by('-fecha')
    tematicas = Publicacion.objects.values_list('idcategoria__id','idcategoria__nombre').order_by('idcategoria__id').distinct('idcategoria__id').exclude(idcategoria__nombre = None)

    return render(request, template, locals())

def DetailBooksView(request, template='publicaciones/detalle_publicacion.html',id=None, uri=None):
    publi = get_object_or_404(Publicacion, id=id)
    # foto_publi = MenuFoto.objects.get(menu=2)
    return render(request, template, locals())
    

class ListBookSimasView(ListView):
    model = Publicacion
    queryset = Publicacion.objects.filter(cidoc=False).order_by('-fecha')
    # paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(ListBookSimasView, self).get_context_data(**kwargs)
        context['foto_publi'] = MenuFoto.objects.get(menu=2)

        return context


class ListBookCidocView(ListView):
    model = Publicacion
    queryset = Publicacion.objects.filter(cidoc=True).order_by('-id')
    # paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super(ListBookCidocView, self).get_context_data(**kwargs)
        context['foto_publi'] = MenuFoto.objects.get(menu=2)

        return context

def publicaciones_categoria(request,template='publicaciones/publicacion_list.html',slug=None):
    object_list = Publicacion.objects.filter(idcategoria__slug=slug)

    return render(request, template, locals())

from haystack.query import SearchQuerySet
from haystack.views import SearchView, search_view_factory
from haystack.forms import ModelSearchForm
def search_publicacion(request):
    sqs = SearchQuerySet().models(Publicacion).order_by('-id')
    view = search_view_factory(
        view_class=SearchView,
        template='search/search_publicacion.html',
        searchqueryset=sqs,
        form_class=ModelSearchForm
        )
    return view(request)

templates/publicaciones/detalle_publicacion.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                {{publi.publicacion}}
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="{% url "publicaciones:publicaciones" %}">
                        Publicaciones
                    </a>
                </li>
                <li>
                    <a href="#">
                        {{publi.publicacion}}
                    </a>
                </li>
            </ul>
        </div>
    </header>

    <section class="single-project small-section">
            <div class="container">
                <div class="single-project--overview">
                    <div class="overview--info-wrapper">
                        <div class="info-wrappper--info">
                            <i class="fas fa-clock"></i>
                            <p>{{publi.fecha|date:"d F Y"}}</p>
                        </div>
                        <div class="info-wrappper--info">
                            <i class="fa fa-user"></i>
                            <a href="">Editorial: {{publi.editorial}}</a>
                        </div>
                        <div class="info-wrappper--info">
                            <i class="fas fa-tag"></i>
                            <p><a href="">{% for obj in object.idcategoria.all %}{{obj}}{% if not forloop.last %},{% endif %}{% endfor %}</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    <!-- About item-->
    <section class="about-item-section">
        <div class="container">
            <div class="row about-item-section--inner-wrapper">
                <div class="col-xl-4 inner-wrapper--image-wrapper bg-size-cover bg-position-center overlay" style="{% thumbnail publi.portada "1280" crop="center" as im %}background-image: url('{{im.url}}'){% empty %}background-image: url('http://via.placeholder.com/1920x1280'){% endthumbnail %}">
                </div>
                <div class="col-xl-8 padding-left">
                    <div class="inner-wrapper--content">
                        <h4>{{publi.publicacion}}</h4>
                        {{publi.resumen|safe}}

                        <div class="container">
                            <div class="row">
                                {% if publi.archivo1 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo1}}" download>Descargar archivo 1</a>
                                </div>
                                {% endif %}

                                {% if publi.archivo2 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo2}}" download>Descargar archivo 2</a>
                                </div>
                                {% endif %}

                                {% if publi.archivo3 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo3}}" download>Descargar archivo 3</a>
                                </div>
                                {% endif %}
                            </div>
                            <br>
                            <div class="row">
                                {% if publi.archivo4 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo4}}" download>Descargar archivo 4</a>
                                </div>
                                {% endif %}
                                {% if publi.archivo5 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo5}}" download>Descargar archivo 5</a>
                                </div>
                                {% endif %}
                                {% if publi.archivo6 %}
                                <div class="button-wrapper col-xl-4">
                                    <a class="button btn-type-2" href="/media/{{publi.archivo6}}" download>Descargar archivo 6</a>
                                </div>
                                {% endif %}
                            </div>
                        </div>



                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

templates/publicaciones/publicacion_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<style>
    .content--title-subtitle h3 {
        font-size: 18px !important;
    }
</style>
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                Publicaciones
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="#">
                        Publicaciones
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Portfolio -->
    <section class="portfolio-metro small-section">
        <div class="container">
            <div class="buttons-sort">
                <a href="{% url 'publicaciones:publicaciones' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
                {% for obj in tematicas %}
                    <a href="{% url 'publicaciones:filtro-publicaciones' obj.0 %}" class="buttons-sort--button">{{obj.1}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="three-column-container">
            <div class="grid" data-grid-layout-mode="masonry" data-grid-transition="0.6" data-grid-stagger="80">
                {% paginate 16 object_list %}
                {% for obj in object_list %}
                <div class="grid--grid-item grid--grid-item-25">
                    <div class="scale-3d--wrapper">
                        <div class="grid-item--grid-inner scale-3d-hover-effect tilt-wrapper"
                                data-tilt-value="5" data-tilt-speed="1200"
                                data-tilt-scale="1" data-tilt-perspective="600">
                            {% thumbnail obj.portada "360x500" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% empty %}
                            <img src="http://via.placeholder.com/360x500" alt="" class="img-fluid">
                            {% endthumbnail %}
                            <a class="grid-inner--description-wrapper" href="{% url 'publicaciones:detalle-publicacion' obj.id obj.uri %}">
                                <div class="description-wrapper--content">
                                    <div class="content--tag">
                                        <p>{{obj.idcategoria.first}}</p>
                                    </div>
                                    <div class="content--title-subtitle">
                                        <h3>{{obj.publicacion}}</h3>
                                    </div>
                                    <div class="content--date">
                                        <p>{{obj.fecha|date:"d F Y"}}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% comment %} agregar css a paginado {% endcomment %}
            {% show_pages %}
        </div>
    </section>
</div>
{% endblock content %}