blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView', 
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

noticias/urls.py
from django.urls import path
from .views import *

app_name = 'noticias'

urlpatterns =   [
    path('', HomePageView, name = "home"),
    # path('portafolio/servicios/', ListServiceView.as_view(), name = "servicios"),
    # path('portafolio/sistemas/', ListPortfolioView.as_view(), name = "portafolio1"),
    path('historia-simas/', HistoriaPageView.as_view(), name = "historia"),
    # path('quienes-somos/', QuienesPageView.as_view(), name = "somos"),
    path('noticias/', ListNewsView.as_view(), name = "noticias"),
   	path('noticias/<int:id>/<str:uri>/', DetailNewsView, name = "detalle-noticia"),
    path('contactenos/', ContactenosPageView.as_view(), name = "contactenos"),
    path('noticias/categoria/<str:slug>', notas_categoria, name = "list-noticia-cat")
]


publicaciones/urls.py
from django.urls import path, include
from .views import *

app_name = 'publicaciones'

urlpatterns = [
    path('publicaciones/', ListBooksView, name ='publicaciones'),
    path('publicaciones/filtro/<id>', FiltroListBooksView, name ='filtro-publicaciones'),
    path('publicaciones/<int:id>/<str:uri>/', DetailBooksView, name ='detalle-publicacion'),
    # path('publicaciones/simas/', ListBookSimasView.as_view(), name ='publicaciones'),
    # path('publicaciones/cidoc/', ListBookCidocView.as_view(), name ='publicaciones'),
    path('publicaciones/categoria/<str:slug>', publicaciones_categoria, name = "list-publicaciones-cat")
]



""" urlpatterns = patterns(
    'publicaciones.views',
    url(r'^publicaciones/$', ListBooksView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/(?P<id>[0-9]+)/(?P<uri>[-\w]+)/$',
        'DetailBooksView', name='detalle-publicacion'),
    url(r'^publicaciones/simas/$', ListBookSimasView.as_view(),
        name='publicaciones'),
    url(r'^publicaciones/cidoc/$', ListBookCidocView.as_view(),
        name='publicaciones'),
)
 """

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),    
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

templates/search/search_notas.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% load embed_video_tags %}
{% load el_pagination_tags %}
{% block extra_css %}
<style>
.pagination>.active{
	background: #089c7b;
    color: #fff;
    border-color: #089c7b;
}
.page-link {
    color: #888;
    border: 2px solid rgba(74,156,124,0.38);
    -webkit-transition: all 0.4s ease;
    -moz-transition: all 0.4s ease;
    -o-transition: all 0.4s ease;
    transition: all 0.4s ease;
}

.page-link:hover {
    background: #089c7b;
    color: #fff;
    border-color: #089c7b;
    -moz-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    -webkit-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}
</style>
{% endblock extra_css %}

{% block content %}
<div class="breadcrumb-area shadow dark bg-fixed text-center color-white">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 text-left">
                <h2 >Actualidad</h2>
            </div>
            <div class="col-md-6 col-sm-6 text-right">
                <ul class="breadcrumb">
                    <li><a href="/">Inicio</a></li>
                    <li class="active">Actualidad</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="area-noticia padding-page bg-gris ">
    <div class="buscador-publicacion">
        <div class="container">
            <div class="row">
                <div class="col-md-2"><a href="/noticias/" class="btn form-control"><i class="fa fa-arrow-left" aria-hidden="true"></i> Ver todos</a></div>
                <div class="col-md-4">
                    <form id="search-form" action="/notas/busqueda/" method="GET">
                        <div class="input-group">
                            {{search.q}}
                            <span class="input-group-btn">
                                <input value="Buscar" id="submit-button" class="btn form-control" type="submit">
                            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
          {% for result in page.object_list %}
            <div class="col-md-6">
                <div class="noticia mrb-20">
                    {% if not result.object.url %}
                    <div class="img-noticia">
                        <figure class="figure">
                            {% thumbnail result.object.foto "348x209" crop="center" as img %}
                                <img class="img-responsive figure-img" src="{{img.url}}" alt="" >
                            {% empty %}
                                <img class="img-responsive figure-img" src="https://place-hold.it/348x209" alt="" >
                            {% endthumbnail %} 
                        </figure>
                    </div>
                    {%elif result.object.url %}
                    <div class="video-noticia">
                        <!--<iframe width="100%" height="315" src="{{obj.url}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>-->
                        {% video result.object.url '100% x 315px' %}
                    </div>
                    {% else %}
                    <div class="img-noticia">
                        <figure class="figure">
                            <img class="img-responsive figure-img" src="https://place-hold.it/348x209" alt="" >
                        </figure>
                    </div>
                        
                    {% endif %}
                    <div class="info-noticia box-shadow">
                        <div class="info-title no-border mb-0 pb-0">
                            <div class="date">
                                <span>{{result.object.fecha|date:"d"}}</span> 
                                <span>{{result.object.fecha|date:"M"}}</span>
                                <span>{{result.object.fecha|date:"Y"}}</span>
                            </div>
                            <div class="title">
                                <h5 class="mrb-20"><a href="{% url 'noticias:detalle-noticia' result.object.id result.object.uri %}">{{result.object.noticia}}</a></h5>
                                <div class="meta">
                                    <div class="position-relative">
                                        {% comment %} <span class="round-avatar">
                                            {% thumbnail obj.idautor.imagen "42x42" crop="center" as im %}
                                            <img src="{{ im.url }}" class="img-responsive" alt="{{obj.idautor}}">
                                            {% empty %}
                                            <img src="https://place-hold.it/42x42" class="img-responsive" alt="{{obj.idautor}}">
                                            {% endthumbnail %}
                                        </span> {% endcomment %}
                                        <p class>
                                        {{result.object.idautor}}
                                        </p>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        <nav class="paginador mrt-30">
                <ul class="pagination justify-content-center">
                   {% if page.has_previous or page.has_next %}

                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}" class="endless_page_link">{% endif %}{% if page.has_previous %}< </a>{% endif %}
                    <span class="endless_page_current">{{ page.number }} de {{ page.paginator.num_pages }}</span>

                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}" class="endless_page_link">{% endif %} {% if page.has_next %}> </a>{% endif %}

                    {% endif %}
                </ul>
            </nav>
    </div>
</div>

{% endblock content %}
{% block extra_js %}
<script>
    $(".menu-3").addClass("active");
    $("#id_q").addClass("form-control");
    $("#id_q").val("{{request.GET.q}}");
    $(".endless_page_link").addClass("page-link page-item");
    $(".endless_page_current").addClass("page-link active page-item");
</script>
{% endblock extra_js %}

templates/search/search_publicacion.html
{% extends "base.html" %}
{% load thumbnail %}
{% load staticfiles %}
{% load el_pagination_tags %}

{% block extra_css %}
<style>
.pagination>.active{
	background: #089c7b;
    color: #fff;
    border-color: #089c7b;
}
.page-link {
    color: #888;
    border: 2px solid rgba(74,156,124,0.38);
    -webkit-transition: all 0.4s ease;
    -moz-transition: all 0.4s ease;
    -o-transition: all 0.4s ease;
    transition: all 0.4s ease;
}

.page-link:hover {
    background: #089c7b;
    color: #fff;
    border-color: #089c7b;
    -moz-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    -webkit-box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}
</style>
{% endblock extra_css %}

{% block content %}
<div class="breadcrumb-area shadow dark bg-fixed text-center  color-white" >
  	<div class="container">
		<div class="row">
			<div class="col-md-6 col-sm-6 text-left">
				<h2 >Publicaciones</h2>
			</div>
			<div class="col-md-6 col-sm-6 text-right">
				<ul class="breadcrumb">
					<li><a href="/">Inicio</a></li>
					<li class="active">Publicaciones</li>
				</ul>
			</div>
		</div>
  	</div>
</div>

<div class="area-publicaciones bg-gris pdb-70">
	<div class="buscador-publicacion">
		<div class="container">
			<div class="row">
				<div class="col-md-2"><a href="/publicaciones/" class="btn form-control"><i class="fa fa-arrow-left" aria-hidden="true"></i> Ver todos</a></div>
				<div class="col-md-4">
					<form id="search-form" action="/publicaciones/busqueda/" method="GET">
                        <div class="input-group">
                            {{search.q}}
                            <span class="input-group-btn">
                                <input value="Buscar" id="submit-button" class="btn form-control" type="submit">
                            </span>
                        </div>
                    </form>
				</div>
				<!--<div class="col-md-8">
					<div class="type-biblioteca text-right">
						{% if request.path == '/publicaciones/cidoc/' %}
							<a href="/publicaciones/cidoc/" class="active">
								CIDOC
							</a>
						{% else %}
							<a href="/publicaciones/cidoc/" class="center">
								CIDOC
							</a>
						{%endif%}
						{% if request.path == '/publicaciones/simas/' %}
							<a href="/publicaciones/simas/" class="active">
								SIMAS
							</a>
						{% else %}
							<a href="/publicaciones/simas/" class="center">
								SIMAS
							</a>
						{%endif%}
						
					</div>
				</div>-->
			</div>
		</div>
	</div>
	<div class="list-publicaciones">
		<div class="container">
			<div class="row">
				{% if page.object_list %}
				{% for result in page.object_list %}
				<div class="col-md-3">
					<figure class="item-box box-shadow">
						{% if result.object.portada %}
						{% thumbnail result.object.portada "350x453" crop="10%" as img %} 
						<img src="{{img.url}}" class="img-responsive" alt="...">
						{% endthumbnail %}
						{%else%}
						<img src="https://place-hold.it/350x453" class="img-responsive" alt="...">
						{%endif%}
						<figcaption class="item-hover">
							<h6>{{result.object.publicacion|truncatechars:68}}</h6>
							<a href="{% url 'publicaciones:detalle-publicacion' result.object.id result.object.uri %}">Ver</a> 
						</figcaption>
					</figure>
				</div>
				{%endfor%}
			{% else %}
			No existen resultados
			{% endif %}
			</div>
			<nav class="paginador mrt-30">
				<ul class="pagination justify-content-center">
				  <!--<li class="page-item">
					<a class="page-link" href="#"><i class="fa fa-angle-left"></i></a>
				  </li>
				  <li class="page-item active"><a class="page-link" href="#">1</a></li>
				  <li class="page-item"><a class="page-link" href="#">2</a></li>
				  <li class="page-item disabled"><a class="page-link">...</a></li>
				  <li class="page-item"><a class="page-link" href="#">80</a></li>
				  <li class="page-item"><a class="page-link" href="#">81</a></li>
				  <li class="page-item">
					<a class="page-link" href="#"><i class="fa fa-angle-right"></i></a>
				  </li>-->
				   {% if page.has_previous or page.has_next %}

                    {% if page.has_previous %}<a href="?q={{ query }}&amp;page={{ page.previous_page_number }}" class="endless_page_link">{% endif %}{% if page.has_previous %}< </a>{% endif %}
                    <span class="endless_page_current">{{ page.number }} de {{ page.paginator.num_pages }}</span>

                    {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}" class="endless_page_link">{% endif %} {% if page.has_next %}> </a>{% endif %}

                    {% endif %}
				</ul>
			</nav>
		</div>
		
	</div>
</div>

{% endblock content %}
{% block extra_js %}
<script>
	$(".menu-5").addClass("active");
	$("#id_q").addClass("form-control");
	$("#id_q").val("{{request.GET.q}}");
    $(".endless_page_link").addClass("page-link page-item");
    $(".endless_page_current").addClass("page-link active page-item");
</script>
{% endblock extra_js %}