blogs/urls.py
from django.urls import path, include

from .views import ListBlogsView, DetailBlogsView, blogs_filtrados

app_name = 'blogs'

urlpatterns = [
    path('blogs/',ListBlogsView.as_view(), name='blogs'),
   	path('blogs/<int:id>/<str:uri>/', DetailBlogsView, name='detalle-blog'),
    path('blogs/filtrar/', blogs_filtrados, name='blog-filtro'),

]


#  patterns('blogs.views',
#     url(r'^blogs/$', ListBlogsView.as_view(), name='blogs'),
#     url(r'^blogs/(?P<id>[0-9]+)/(?P<uri>[-_\w]+)/$', 'DetailBlogsView', 
#     									name='detalle-blog'),
#     url(r'^blogs/filtrar/$', 'blogs_filtrados', name='blog-filtro'),

# )

multimedia/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('galerias-imagenes/', GaleriaImgListView, name = "list-galeria"),
	path('galerias-imagenes/filtro/<id>', filtro_galeria, name = "filtro-galeria"),
	path('galerias-imagenes/<slug>', detalle_galeria, name = "detalle-galeria"),
	path('videos/', videos, name="videos"),
]

websimas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from noticias.views import contacto_ajax, get_deptos, search_notas, get_img_servicios,get_blogs,list_portfolio,filtro_portafolio,detalle_portafolio
from django.conf.urls import url
from django.views.generic import TemplateView
from otras.views import *
from proyectos.views import *
from publicaciones.views import *

admin.site.site_header = "Administración SIMAS"
admin.site.site_title = "Administración SIMAS"

urlpatterns = [

    path('', include(('publicaciones.urls','publicaciones'), namespace='publicaciones')),
    path('', include(('noticias.urls','noticias'), namespace='noticias')),
    path('', include(('blogs.urls','blogs'), namespace='blogs')),
    path('busqueda/', include(('googlesearch.urls','googlesearch'), namespace='googlesearch')),    
    path('contacto_ajax/', contacto_ajax, name='contacto_ajax'),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('_nested_admin/', include('nested_admin.urls')),
    path('', include(('multimedia.urls','multimedia'), namespace='multimedia')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('servicios/<str:uri>/', servicios, name='servicios'),
    # path('publicaciones/busqueda/', include('haystack.urls')),
    path('publicaciones/busqueda/', search_publicacion, name = 'search-publicacion'),
    path('notas/busqueda/', search_notas, name = 'search-notas'),
    path('ajax/deptos/', get_deptos, name='get-deptos'),
    path('proyectos/', list_proyectos, name = 'list-proyectos'),
    path('proyectos/<str:slug>/', detalle_proyecto, name = 'detalle-proyecto'),
    path('ajax/servicios/', get_img_servicios, name='get-img-servicios'),
    path('ajax/blogs/', get_blogs, name='get-blogs'),
    path('portafolio/', list_portfolio, name='list-portafolio'),
    path('portafolio/<slug>', detalle_portafolio, name='detalle-portafolio'),
    path('portafolio/filtro/<id>', filtro_portafolio, name='filtro-portafolio'),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT )
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT )

templates/galeria/detalle.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
<style media="screen">
  .text-img {
    position: absolute;
    bottom: 0;
    width: 100%;
    height: 20px;
    text-align: center;
    color:white;
    background-color: var(--primary-color-2)
  }
</style>
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                {{object.titulo}}
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="{% url 'multimedia:list-galeria' %}">
                        Galerías
                    </a>
                </li>
                <li>
                    <a href="#">
                        {{object.titulo}}
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Single Project 1 -->
    <section class="single-project small-section">
        <div class="container">
            <div class="single-project--overview">
                <div class="overview--title">
                    <h2>{{object.titulo}}</h2>
                </div>
                <div class="overview--info-wrapper">
                    <div class="info-wrappper--info">
                        <i class="fas fa-clock"></i>
                        <p>{{object.fecha|date:"d F Y"}}</p>
                    </div>
                    <div class="info-wrappper--info">
                        <i class="fas fa-tag"></i>
                        <p><a href="">{% for obj in object.categoria.all %}{{obj}}{% if not forloop.last %},{% endif %}{% endfor %}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% if object.descripcion %}
    <!-- About item text -->
    <section class="about-item-text-section">
        <div class="container">
            <div class="row">
                <div class="col">
                    <div class="inner-wrapper--content">
                        {{object.descripcion|safe}}
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endif %}
    <!-- Accordion gallery-->
    <section class="accordion-gallery-section">
        <div class="accordion-gallery">
            <div class="accordion-gallery--inner-wrapper">
                <div class="inner-wrapper--items-wrapper">
                    {% for obj in object.fotosgaleria_set.all %}
                    <div class="items-wrapper--item">
                        <div class="item--image-wrapper">
                            <div class="image-wrapper--image-inner">
                                <div class="image-inner--image">
                                    <div class="image--background"
                                        style="{% thumbnail obj.archivo "1920x1280" crop="center" as im %}background-image: url({{ im.url }}){% empty %}background-image: url('http://via.placeholder.com/1920x1280'){% endthumbnail %}">
                                        <div class="text-img">
                                          <span>{{obj.nombre}}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="items-wrapper--item-sizer"></div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock content %}

templates/galeria/galeria.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load el_pagination_tags %}

{% block content %}
<!-- Page Content -->
<div class="content-page-wrapper">
    <!-- Header Breadcrumbs-->
    <header class="breadcrumbs-type-1">
        <div class="container breadcrumbs--breadcrumbs-inner">
            <h1 class="breadcrumbs-inner--page-title">
                Galería
            </h1>
            <ul class="breadcrumbs-inner--breadcrumbs-list">
                <li>
                    <a href="/">
                        Inicio
                    </a>
                </li>
                <li>
                    <a href="#">
                        Galería
                    </a>
                </li>
            </ul>
        </div>
    </header>
    <!-- Portfolio -->
    <section class="portfolio-metro small-section">
        <div class="container">
            <div class="buttons-sort">
                <a href="{% url 'multimedia:list-galeria' %}" class="buttons-sort--button active-button" data-filter="*">Todos</a>
                {% for obj in tematicas %}
                    <a href="{% url 'multimedia:filtro-galeria' obj.0 %}" class="buttons-sort--button">{{obj.1}}</a>
                {% endfor %}
            </div>
        </div>
        <div class="three-column-container">
            <div class="grid" data-grid-layout-mode="masonry" data-grid-transition="0.6" data-grid-stagger="80">
                {% paginate 15 object_list %}
                {% for obj in object_list %}
                <div class="grid--grid-item grid--grid-item-33 web creative">
                    <div class="scale-3d--wrapper">
                        <div class="grid-item--grid-inner scale-3d-hover-effect tilt-wrapper"
                                data-tilt-value="5" data-tilt-speed="1200"
                                data-tilt-scale="1" data-tilt-perspective="600">
                            {% thumbnail obj.portada "1920x1280" crop="center" as im %}
                            <img src="{{ im.url }}" alt="" class="img-fluid">
                            {% endthumbnail %}
                            <a class="grid-inner--description-wrapper" href="{% url 'multimedia:detalle-galeria' obj.slug %}">
                                <div class="description-wrapper--content">
                                    <div class="content--tag">
                                        <p>{{obj.categoria.first}}</p>
                                    </div>
                                    <div class="content--title-subtitle">
                                        <h3>{{obj.titulo}}</h3>
                                    </div>
                                    <div class="content--date">
                                        <p>{{obj.fecha|date:"d F Y"}}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% comment %} agregar css a paginado {% endcomment %}
            {% show_pages %}
        </div>
    </section>
</div>
{% endblock content %}